# Generated by Django 4.0.1 on 2022-01-19 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_risks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='risks',
        ),
    ]
