# Generated by Django 4.0.1 on 2022-01-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="risk",
            name="probability_percentage",
            field=models.CharField(
                choices=[
                    (1, "10%"),
                    (2, "20%"),
                    (3, "30%"),
                    (4, "40%"),
                    (5, "50%"),
                    (6, "60%"),
                    (7, "70%"),
                    (8, "80%"),
                    (9, "90%"),
                    (10, "100%"),
                ],
                default=1,
                max_length=6,
            ),
        ),
    ]
