# Generated by Django 4.0.1 on 2022-01-10 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_risk_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='projects.project'),
        ),
    ]
