# Generated by Django 4.0.1 on 2022-01-16 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_projects"),
        ("projects", "0008_historicalrisk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrisk",
            name="priority",
            field=models.CharField(
                choices=[("1", "Low"), ("2", "Medium"), ("3", "High")], max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="historicalrisk",
            name="probability_percentage",
            field=models.CharField(
                choices=[
                    ("0", "0%"),
                    ("1", "10%"),
                    ("2", "20%"),
                    ("3", "30%"),
                    ("4", "40%"),
                    ("5", "50%"),
                    ("6", "60%"),
                    ("7", "70%"),
                    ("8", "80%"),
                    ("9", "90%"),
                    ("10", "100%"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrisk",
            name="user_assigned",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="users.profile",
            ),
        ),
        migrations.AlterField(
            model_name="risk",
            name="priority",
            field=models.CharField(
                choices=[("1", "Low"), ("2", "Medium"), ("3", "High")], max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="risk",
            name="probability_percentage",
            field=models.CharField(
                choices=[
                    ("0", "0%"),
                    ("1", "10%"),
                    ("2", "20%"),
                    ("3", "30%"),
                    ("4", "40%"),
                    ("5", "50%"),
                    ("6", "60%"),
                    ("7", "70%"),
                    ("8", "80%"),
                    ("9", "90%"),
                    ("10", "100%"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="risk",
            name="user_assigned",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.profile",
            ),
        ),
    ]
