# Generated by Django 4.0.1 on 2022-01-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_profile_projects_remove_profile_risks"),
        ("projects", "0010_remove_historicalrisk_user_assigned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="users_assigned",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="users.Profile"
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="resolvers_assigned",
            field=models.ManyToManyField(
                blank=True, related_name="resolvers_assigned", to="users.Profile"
            ),
        ),
    ]
